name: integrador_lagata
description: Sistema de facturación para La Gata
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Networking & API
  http: ^1.1.0
  dio: ^5.4.0

  # Local Storage & Session
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # Navigation
  go_router: ^12.1.3

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.2.2
  uuid: ^4.2.1
  flutter_dotenv: ^5.1.0

  # PDF Generation
  pdf: ^3.10.7
  path_provider: ^2.1.1
  open_file: ^3.3.2
  share_plus: ^7.2.1

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

  # Charts & Data Visualization
  fl_chart: ^0.65.0

  # Firebase, Maps, Notifications, Images (comentados temporalmente)
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.1.6
  # google_maps_flutter: ^2.5.3
  # geolocator: ^10.1.0
  # geocoding: ^2.1.1
  # cached_network_image: ^3.3.0
  # image_picker: ^1.0.4
  # flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # Assets
  assets:
    - .env
    - web/assets/.env
  
  # Fonts configuration for web
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
